group:
  - files:
      - source: configs/FUNDING.yml
        dest: .github/FUNDING.yml
    repos: |
      tarioch/pre-commit-hooks
      tarioch/beancounttools
      tarioch/xirr
  - files:
      - source: configs/pr-labeler.yml
        dest: .github/pr-labeler.yml
      - source: configs/workflows/pr-labeler.yml
        dest: .github/pr-labeler.yml
    repos: |
      tarioch/pre-commit-hooks
      tarioch/beancounttools
      tarioch/xirr